version: "3.5"
services:
  fakelog:
    build: .
    environment:
      - SUBDOMAIN_OFFSET=3
    ports:
      - "3000:3000"
    networks:
      - internal_network

networks:
  internal_network:
    external:
      name: wulkanowy_network
